# Generated by Django 4.1.3 on 2022-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_account', models.IntegerField(verbose_name='Id Identificação')),
                ('balance_transfer', models.PositiveIntegerField(verbose_name='Saldo Transferido')),
                ('account_destiny', models.IntegerField(verbose_name='Conta transferida')),
                ('name_destinatary', models.CharField(max_length=250, verbose_name='Nome destinatário')),
            ],
        ),
    ]
