# Generated by Django 4.1.3 on 2022-11-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtransfer',
            name='email_destinatary',
            field=models.EmailField(default=1, max_length=250, verbose_name='Email destinatário'),
            preserve_default=False,
        ),
    ]
