# Generated by Django 4.1.3 on 2022-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name_complete',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
